### PR TITLE
Fix for uploading featured and media image #337

### PR DESCRIPTION
**Pull request by Sil-B**

### CODE REVIEW

**Comment by axelosd** [comment]
Needs slash after 'magefan_blog' to work
->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'magefan_blog/' . $file;

**Comment by Sil-B** [comment]
@axelosd yes, typo

**Comment by axelosd** [comment]
Magefan just upload fix for this
[https://magefan.com/blog-featured-images-are-broken-after-uploading-in-magento-2](https://magefan.com/blog-featured-images-are-broken-after-uploading-in-magento-2)

**Comment by ihorvansach** [comment]
@axelosd , @Sil-B ,

This fix cannot be approved as it will break thousands of stores. 
featured_img should be saved with "magefan_blog/" in the database, e.g. "magefan_blog/image_file.jpeg"
If someone with existing blog will upload this fix, he will get wrong URL, like
http://domain.com/pub/media/magefan_blog/magefan_blog/0.jpeg (with double magefan_blog)

Also we cannot reproduce this issue https://github.com/magefan/module-blog/issues/337 on clean Magento installation + Blog extension.  Please make sure that no other custom extension on your instance breaks the Magefan_Blog module.

@axelosd , as you aware of this article https://magefan.com/blog-featured-images-are-broken-after-uploading-in-magento-2 you should know that you will have this issue if use Amasty Layered navigation, and the fix is in the article. So the blog extension is a wrong place to fix it. Today we have received reply from Amasty and they said that released a new Amasty_Shopby 2.14.7, so If you have Amasty/Shopby, to fix the issue - update this module.

**Comment by Sil-B** [comment]
@ihorvansach thanks for the "amasty" fix!

**Pull request closed without merging**
