### PR TITLE
AddThis template and configuration

### PR DESCRIPTION
**Pull request by andreygolovin**
Hello, thanks for great module.

Please check this PR if you will have some time:
1. AddThis JS init code moved to template
2. AddThis admin configuration added

### CODE REVIEW

**Comment by pivulic** [comment]
👍

**Comment by magefan** [comment]
@andreygolovin thank you for contribution!

**Comment by pivulic** [comment]
Can you also release a new version in https://packagist.org/packages/magefan/module-blog, e.g. 2.2.1?

**Comment by magefan** [comment]
@pivulic, yes sure. (https://github.com/magefan/module-blog/releases/tag/2.2.1)

**Comment by pivulic** [comment]
As usual, thanks for the quick help!

**Pull request merged**
